/* include/IL/config.h.  Generated by configure.  */
/* include/IL/config.h.in.  Generated automatically from configure.in by autoheader.  */
#ifndef __CONFIG_H__
#define __CONFIG_H__

//#define IL_NO_BMP
//#define IL_NO_GIF
//#define IL_NO_ICO
//#define IL_NO_JPG
//#define IL_NO_PNG


#define IL_NO_CUT
#define IL_NO_CHEAD
#define IL_NO_DCX
#define IL_NO_DDS
#define IL_NO_DOOM
#define IL_NO_LIF
#define IL_NO_MDL
#define IL_NO_MNG
#define IL_NO_PCD
#define IL_NO_PCX
#define IL_NO_PIC
#define IL_NO_PIX
#define IL_NO_PNM
#define IL_NO_PSD
#define IL_NO_PSP
#define IL_NO_PXR
#define IL_NO_RAW
#define IL_NO_SGI
#define IL_NO_TGA
#define IL_NO_TIF
#define IL_NO_WAL
#define IL_NO_XPM
#define IL_NO_LCMS

#undef IL_USE_JPEGLIB_UNMODIFIED
#define IL_USE_JPEGLIB_UNMODIFIED 1
#define IL_NO_LCMS

/* Supported api (ilut) */


/* #undef ILUT_USE_ALLEGRO */
//#define ILUT_USE_DIRECTX8 1
//#define ILUT_USE_DIRECTX9 1
//#define ILUT_USE_OPENGL 1
//#define ILUT_USE_SDL 1
#define ILUT_USE_WIN32 1


/* Define if you have the <dlfcn.h> header file. */
/* #undef HAVE_DLFCN_H */

/* Name of package */
#define PACKAGE "DevIL"

/* Version number of package */
#define VERSION "1.6.6"

/* Define if your processor stores words with the most significant byte first
   (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Define if the X Window System is missing or not being used. */
#define X_DISPLAY_MISSING 1
#endif /* __CONFIG_H__ */
